### ISSUE TITLE
Can't get the graph to display any data

### ISSUE THREAD

**Issue by NathanNovak** [Flagsmith/react-native-performance-monitor#21]
Looks like a great tool but when I remount there is nothing on the graph. I can't even get a baseline.  
Tried on a iPad simulator and followed the instructions but nothing works.  Can you let me know what I'm doing wrong?

**Comment by frodoe7** [comment]
Me too , nothing shown on the chart

**Comment by kyle-ssg** [comment]
Hey there. Could you let me know what react native version is being used? Or better yet a very basic repository that demonstrates this?


Quite a few projects use this currently so I guess potentially it's a breaking change in the profiler for React Native.

Thanks

**Comment by kyle-ssg** [comment]
One thing to check before this, ensure that when the performance monitor server starts that it is accessible via 127.0.0.1:8125, if it's not you'll have to use whatever IP you can like the instructions in the readme

"By default the server is listening on port 8125 for event updates and 8126 for websocket. If you need to configure the port, because you are tunneling your request or similar, and or disable the Websocket communication, you can do it like this:"

```
export default withPerformanceMonitor(AwesomeChat, 'AwesomeChat', '192.168.1.10', undefined, undefined, 80, false);
```
